ABI_YIELDBASIS_Stake_Zap = [
    {"inputs":[
        {"name":"gauge","type":"address"},
        {"name":"assets","type":"uint256"},
        {"name":"debt","type":"uint256"},
        {"name":"min_shares","type":"uint256"}],"name":"deposit_and_stake",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"gauge","type":"address"},
        {"name":"assets","type":"uint256"},
        {"name":"debt","type":"uint256"},
        {"name":"min_shares","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"deposit_and_stake",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"gauge","type":"address"},
        {"name":"shares","type":"uint256"},
        {"name":"min_assets","type":"uint256"}],"name":"withdraw_and_unstake",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"gauge","type":"address"},
        {"name":"shares","type":"uint256"},
        {"name":"min_assets","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"withdraw_and_unstake",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"}]

ABI_YIELDBASIS_cbBTC_Leverage = [
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"staker","type":"address"}],"name":"SetStaker","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"receiver","type":"address"},
        {"indexed":False,"name":"amount","type":"uint256"}],"name":"WithdrawAdminFees","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"allocator","type":"address"},
        {"indexed":False,"name":"stablecoin_allocation","type":"uint256"},
        {"indexed":False,"name":"stablecoin_allocated","type":"uint256"}],"name":"AllocateStablecoins","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"sender","type":"address"},
        {"indexed":False,"name":"amount","type":"uint256"},
        {"indexed":False,"name":"min_amount","type":"uint256"},
        {"indexed":False,"name":"discount","type":"uint256"}],"name":"DistributeBorrowerFees","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"sender","type":"address"},
        {"indexed":True,"name":"owner","type":"address"},
        {"indexed":False,"name":"assets","type":"uint256"},
        {"indexed":False,"name":"shares","type":"uint256"}],"name":"Deposit","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"sender","type":"address"},
        {"indexed":True,"name":"receiver","type":"address"},
        {"indexed":True,"name":"owner","type":"address"},
        {"indexed":False,"name":"assets","type":"uint256"},
        {"indexed":False,"name":"shares","type":"uint256"}],"name":"Withdraw","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"admin","type":"address"}],"name":"SetAdmin","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"sender","type":"address"},
        {"indexed":True,"name":"receiver","type":"address"},
        {"indexed":False,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"owner","type":"address"},
        {"indexed":True,"name":"spender","type":"address"},
        {"indexed":False,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},
    {"inputs":[],"name":"min_admin_fee",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"assets","type":"uint256"},
        {"name":"debt","type":"uint256"}],"name":"preview_deposit",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"assets","type":"uint256"},
        {"name":"debt","type":"uint256"},
        {"name":"raise_overflow","type":"bool"}],"name":"preview_deposit",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"tokens","type":"uint256"}],"name":"preview_withdraw",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"assets","type":"uint256"},
        {"name":"debt","type":"uint256"},
        {"name":"min_shares","type":"uint256"}],"name":"deposit",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"assets","type":"uint256"},
        {"name":"debt","type":"uint256"},
        {"name":"min_shares","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"deposit",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"shares","type":"uint256"},
        {"name":"min_assets","type":"uint256"}],"name":"withdraw",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"shares","type":"uint256"},
        {"name":"min_assets","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"withdraw",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"shares","type":"uint256"}],"name":"preview_emergency_withdraw",
    "outputs":[
        {"name":"","type":"uint256"},
        {"name":"","type":"int256"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"name":"shares","type":"uint256"}],"name":"emergency_withdraw","outputs":[{"name":"","type":"uint256"},{"name":"","type":"int256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"shares","type":"uint256"},{"name":"receiver","type":"address"}],"name":"emergency_withdraw","outputs":[{"name":"","type":"uint256"},{"name":"","type":"int256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"shares","type":"uint256"},{"name":"receiver","type":"address"},{"name":"owner","type":"address"}],"name":"emergency_withdraw","outputs":[{"name":"","type":"uint256"},{"name":"","type":"int256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"checkpoint_staker_rebase","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"updated_balances","outputs":[{"name":"","type":"uint256"},{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"pricePerShare","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"name":"amm","type":"address"}],"name":"set_amm","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"new_admin","type":"address"}],"name":"set_admin","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"rate","type":"uint256"}],"name":"set_rate","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"fee","type":"uint256"}],"name":"set_amm_fee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"allocate_stablecoins","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"limit","type":"uint256"}],"name":"allocate_stablecoins","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"distribute_borrower_fees","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"discount","type":"uint256"}],"name":"distribute_borrower_fees","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"withdraw_admin_fees","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"staker","type":"address"}],"name":"set_staker","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"is_killed","type":"bool"}],"name":"set_killed","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"is_killed","outputs":[{"name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"CRYPTOPOOL","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"STABLECOIN","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"ASSET_TOKEN","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"admin","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"amm","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"agg","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"staker","outputs":[{"name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"liquidity","outputs":[{"components":[{"name":"admin","type":"int256"},{"name":"total","type":"uint256"},{"name":"ideal_staked","type":"uint256"},{"name":"staked","type":"uint256"}],"name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"name":"arg0","type":"address"},{"name":"arg1","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"name":"arg0","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"stablecoin_allocation","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"stablecoin_allocated","outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"name":"asset_token","type":"address"},{"name":"stablecoin","type":"address"},{"name":"cryptopool","type":"address"},{"name":"admin","type":"address"}],"outputs":[],"stateMutability":"nonpayable","type":"constructor"}]

ABI_YIELDBASIS_cbBTC_POOL = [
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"views","type":"address"},
        {"indexed":False,"name":"math","type":"address"}],"name":"SetPeriphery","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"sender","type":"address"},
        {"indexed":True,"name":"receiver","type":"address"},
        {"indexed":False,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"owner","type":"address"},
        {"indexed":True,"name":"spender","type":"address"},
        {"indexed":False,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"buyer","type":"address"},
        {"indexed":False,"name":"sold_id","type":"uint256"},
        {"indexed":False,"name":"tokens_sold","type":"uint256"},
        {"indexed":False,"name":"bought_id","type":"uint256"},
        {"indexed":False,"name":"tokens_bought","type":"uint256"},
        {"indexed":False,"name":"fee","type":"uint256"},
        {"indexed":False,"name":"price_scale","type":"uint256"}],"name":"TokenExchange","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"provider","type":"address"},
        {"indexed":True,"name":"receiver","type":"address"},
        {"indexed":False,"name":"token_amounts","type":"uint256[2]"},
        {"indexed":False,"name":"fee","type":"uint256"},
        {"indexed":False,"name":"token_supply","type":"uint256"},
        {"indexed":False,"name":"price_scale","type":"uint256"}],"name":"AddLiquidity","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"donor","type":"address"},
        {"indexed":False,"name":"token_amounts","type":"uint256[2]"}],"name":"Donation","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"provider","type":"address"},
        {"indexed":False,"name":"token_amounts","type":"uint256[2]"},
        {"indexed":False,"name":"token_supply","type":"uint256"}],"name":"RemoveLiquidity","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"provider","type":"address"},
        {"indexed":False,"name":"token_amount","type":"uint256"},
        {"indexed":False,"name":"coin_index","type":"uint256"},
        {"indexed":False,"name":"coin_amount","type":"uint256"},
        {"indexed":False,"name":"approx_fee","type":"uint256"},
        {"indexed":False,"name":"packed_price_scale","type":"uint256"}],"name":"RemoveLiquidityOne","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"provider","type":"address"},
        {"indexed":False,"name":"lp_token_amount","type":"uint256"},
        {"indexed":False,"name":"token_amounts","type":"uint256[2]"},
        {"indexed":False,"name":"approx_fee","type":"uint256"},
        {"indexed":False,"name":"price_scale","type":"uint256"}],"name":"RemoveLiquidityImbalance","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"mid_fee","type":"uint256"},
        {"indexed":False,"name":"out_fee","type":"uint256"},
        {"indexed":False,"name":"fee_gamma","type":"uint256"},
        {"indexed":False,"name":"allowed_extra_profit","type":"uint256"},
        {"indexed":False,"name":"adjustment_step","type":"uint256"},
        {"indexed":False,"name":"ma_time","type":"uint256"}],"name":"NewParameters","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"initial_A","type":"uint256"},
        {"indexed":False,"name":"future_A","type":"uint256"},
        {"indexed":False,"name":"initial_gamma","type":"uint256"},
        {"indexed":False,"name":"future_gamma","type":"uint256"},
        {"indexed":False,"name":"initial_time","type":"uint256"},
        {"indexed":False,"name":"future_time","type":"uint256"}],"name":"RampAgamma","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"current_A","type":"uint256"},
        {"indexed":False,"name":"current_gamma","type":"uint256"},
        {"indexed":False,"name":"time","type":"uint256"}],"name":"StopRampA","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":True,"name":"admin","type":"address"},
        {"indexed":False,"name":"tokens","type":"uint256[2]"}],"name":"ClaimAdminFee","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"duration","type":"uint256"}],"name":"SetDonationDuration","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"donation_protection_period","type":"uint256"},
        {"indexed":False,"name":"donation_protection_lp_threshold","type":"uint256"},
        {"indexed":False,"name":"donation_shares_max_ratio","type":"uint256"}],"name":"SetDonationProtection","type":"event"},
    {"anonymous":False,"inputs":[
        {"indexed":False,"name":"admin_fee","type":"uint256"}],"name":"SetAdminFee","type":"event"},
    {"inputs":[
        {"name":"i","type":"uint256"},
        {"name":"j","type":"uint256"},
        {"name":"dx","type":"uint256"},
        {"name":"min_dy","type":"uint256"}],"name":"exchange",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"i","type":"uint256"},
        {"name":"j","type":"uint256"},
        {"name":"dx","type":"uint256"},
        {"name":"min_dy","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"exchange",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"i","type":"uint256"},
        {"name":"j","type":"uint256"},
        {"name":"dx","type":"uint256"},
        {"name":"min_dy","type":"uint256"}],"name":"exchange_received",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"i","type":"uint256"},
        {"name":"j","type":"uint256"},
        {"name":"dx","type":"uint256"},
        {"name":"min_dy","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"exchange_received",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"amounts","type":"uint256[2]"},
        {"name":"min_mint_amount","type":"uint256"}],"name":"add_liquidity",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"amounts","type":"uint256[2]"},
        {"name":"min_mint_amount","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"add_liquidity",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"amounts","type":"uint256[2]"},
        {"name":"min_mint_amount","type":"uint256"},
        {"name":"receiver","type":"address"},
        {"name":"donation","type":"bool"}],"name":"add_liquidity",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"amount","type":"uint256"},
        {"name":"min_amounts","type":"uint256[2]"}],"name":"remove_liquidity",
    "outputs":[
        {"name":"","type":"uint256[2]"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"amount","type":"uint256"},
        {"name":"min_amounts","type":"uint256[2]"},
        {"name":"receiver","type":"address"}],"name":"remove_liquidity",
    "outputs":[
        {"name":"","type":"uint256[2]"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"token_amount","type":"uint256"},
        {"name":"i","type":"uint256"},
        {"name":"amount_i","type":"uint256"},
        {"name":"min_amount_j","type":"uint256"}],"name":"remove_liquidity_fixed_out",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"token_amount","type":"uint256"},
        {"name":"i","type":"uint256"},
        {"name":"amount_i","type":"uint256"},
        {"name":"min_amount_j","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"remove_liquidity_fixed_out",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"lp_token_amount","type":"uint256"},
        {"name":"i","type":"uint256"},
        {"name":"min_amount","type":"uint256"}],"name":"remove_liquidity_one_coin",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"lp_token_amount","type":"uint256"},
        {"name":"i","type":"uint256"},
        {"name":"min_amount","type":"uint256"},
        {"name":"receiver","type":"address"}],"name":"remove_liquidity_one_coin",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"user_supply",
     "outputs":[{"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"lp_token_amount","type":"uint256"},
        {"name":"i","type":"uint256"},
        {"name":"amount_i","type":"uint256"}],"name":"calc_withdraw_fixed_out",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"lp_token_amount","type":"uint256"},
        {"name":"i","type":"uint256"}],"name":"calc_withdraw_one_coin",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"_from","type":"address"},
        {"name":"_to","type":"address"},
        {"name":"_value","type":"uint256"}],"name":"transferFrom",
    "outputs":[
        {"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"_to","type":"address"},
        {"name":"_value","type":"uint256"}],"name":"transfer",
    "outputs":[
        {"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"_spender","type":"address"},
        {"name":"_value","type":"uint256"}],"name":"approve",
    "outputs":[
        {"name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"fee_receiver",
     "outputs":[
         {"name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"admin",
     "outputs":[
         {"name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"amounts","type":"uint256[2]"},
        {"name":"deposit","type":"bool"}],"name":"calc_token_amount",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"i","type":"uint256"},
        {"name":"j","type":"uint256"},
        {"name":"dx","type":"uint256"}],"name":"get_dy",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"i","type":"uint256"},
        {"name":"j","type":"uint256"},
        {"name":"dy","type":"uint256"}],"name":"get_dx",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"i","type":"uint256"},
        {"name":"j","type":"uint256"},
        {"name":"dy","type":"uint256"},
        {"name":"n_iter","type":"uint256"}],"name":"get_dx",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"lp_price",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"get_virtual_price",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"price_oracle",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"price_scale",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"fee",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"amounts","type":"uint256[2]"},
        {"name":"xp","type":"uint256[2]"}],"name":"calc_token_fee",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"amounts","type":"uint256[2]"},
        {"name":"xp","type":"uint256[2]"},
        {"name":"donation","type":"bool"}],"name":"calc_token_fee",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"amounts","type":"uint256[2]"},
        {"name":"xp","type":"uint256[2]"},
        {"name":"donation","type":"bool"},
        {"name":"deposit","type":"bool"}],"name":"calc_token_fee",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"A",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"gamma",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"mid_fee",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"out_fee",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"fee_gamma",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"allowed_extra_profit",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"adjustment_step",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"ma_time",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"precisions",
     "outputs":[
         {"name":"","type":"uint256[2]"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"xp","type":"uint256[2]"}],"name":"fee_calc",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"future_A","type":"uint256"},
        {"name":"future_gamma","type":"uint256"},
        {"name":"future_time","type":"uint256"}],"name":"ramp_A_gamma",
    "outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"stop_ramp_A_gamma",
     "outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"_new_mid_fee","type":"uint256"},
        {"name":"_new_out_fee","type":"uint256"},
        {"name":"_new_fee_gamma","type":"uint256"},
        {"name":"_new_allowed_extra_profit","type":"uint256"},
        {"name":"_new_adjustment_step","type":"uint256"},
        {"name":"_new_ma_time","type":"uint256"}],"name":"apply_new_parameters",
    "outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"duration","type":"uint256"}],"name":"set_donation_duration",
    "outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"_period","type":"uint256"},
        {"name":"_threshold","type":"uint256"},
        {"name":"_max_shares_ratio","type":"uint256"}],"name":"set_donation_protection_params",
    "outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"admin_fee","type":"uint256"}],"name":"set_admin_fee",
    "outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[
        {"name":"views","type":"address"},
        {"name":"math","type":"address"}],"name":"set_periphery",
    "outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"MATH",
     "outputs":[
         {"name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"VIEW",
     "outputs":[
         {"name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"arg0","type":"uint256"}],"name":"coins",
    "outputs":[
        {"name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"factory",
     "outputs":[
         {"name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"last_prices",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"last_timestamp",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"initial_A_gamma",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"initial_A_gamma_time",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"future_A_gamma",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"future_A_gamma_time",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"donation_shares",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"donation_shares_max_ratio",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"donation_duration",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"last_donation_release_ts",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"donation_protection_expiry_ts",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"donation_protection_period",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"donation_protection_lp_threshold",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"arg0","type":"uint256"}],"name":"balances",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"D",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"xcp_profit",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"xcp_profit_a",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"virtual_price",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"packed_rebalancing_params",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"packed_fee_params",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"admin_fee",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"name",
     "outputs":[
         {"name":"","type":"string"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"symbol",
     "outputs":[
        {"name":"","type":"string"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"decimals",
     "outputs":[
         {"name":"","type":"uint8"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"version",
     "outputs":[
        {"name":"","type":"string"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"arg0","type":"address"}],"name":"balanceOf",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"arg0","type":"address"},
        {"name":"arg1","type":"address"}],"name":"allowance",
    "outputs":[
        {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"totalSupply",
     "outputs":[
         {"name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[
        {"name":"_name","type":"string"},
        {"name":"_symbol","type":"string"},
        {"name":"_coins","type":"address[2]"},
        {"name":"_math","type":"address"},
        {"name":"_salt","type":"bytes32"},
        {"name":"packed_precisions","type":"uint256"},
        {"name":"packed_gamma_A","type":"uint256"},
        {"name":"packed_fee_params","type":"uint256"},
        {"name":"packed_rebalancing_params","type":"uint256"},
        {"name":"initial_price","type":"uint256"}],
    "outputs":[],"stateMutability":"nonpayable","type":"constructor"}]



ABIs = {
    'YIELDBASIS_Stake_Zap': ABI_YIELDBASIS_Stake_Zap,
    'YIELDBASIS_cbBTC_Leverage': ABI_YIELDBASIS_cbBTC_Leverage,
    'YIELDBASIS_cbBTC_POOL': ABI_YIELDBASIS_cbBTC_POOL
}